package loaders.TreeLoaders;

import gameobjects.GameObject;
import gameobjects.stationarygameobjects.NatureObject;
import loaders.GameObjectLoader;

public class TreeLoaderMapChunkTwentyFour extends MapChunkTreeLoader {
	public GameObject[] treesMapChunkTwentyFour  = new NatureObject[140];

	@Override
	public void loadTrees() {
		startXPosition		          = chunkWidth * 7;
		row 				          = rowThreeStartPosition;
		treesMapChunkTwentyFour[0]   = new NatureObject(startXPosition, row);
		treesMapChunkTwentyFour[1]   = new NatureObject(startXPosition + 1, row);
		treesMapChunkTwentyFour[2]   = new NatureObject(startXPosition + 2, row);
		treesMapChunkTwentyFour[3]   = new NatureObject(startXPosition + 3, row);
		treesMapChunkTwentyFour[4]   = new NatureObject(startXPosition + 4, row);
		treesMapChunkTwentyFour[5]   = new NatureObject(startXPosition + 5, row);
		treesMapChunkTwentyFour[6]   = new NatureObject(startXPosition + 6, row);
		treesMapChunkTwentyFour[7]   = new NatureObject(startXPosition + 7, row);
		treesMapChunkTwentyFour[8]   = new NatureObject(startXPosition + 8, row);
		treesMapChunkTwentyFour[9]   = new NatureObject(startXPosition + 9, row);
		treesMapChunkTwentyFour[10]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyFour[11]  = new NatureObject(startXPosition + 21, row);
		treesMapChunkTwentyFour[12]  = new NatureObject(startXPosition + 22, row);
		treesMapChunkTwentyFour[13]  = new NatureObject(startXPosition + 23, row);
		treesMapChunkTwentyFour[14]  = new NatureObject(startXPosition + 24, row);
		treesMapChunkTwentyFour[15]  = new NatureObject(startXPosition + 25, row);
		treesMapChunkTwentyFour[16]  = new NatureObject(startXPosition + 26, row);
		treesMapChunkTwentyFour[17]  = new NatureObject(startXPosition + 27, row);
		treesMapChunkTwentyFour[18]  = new NatureObject(startXPosition + 28, row);
		treesMapChunkTwentyFour[19]  = new NatureObject(startXPosition + 29, row);
		treesMapChunkTwentyFour[20]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyFour[21]  = new NatureObject(startXPosition + 41, row);
		treesMapChunkTwentyFour[22]  = new NatureObject(startXPosition + 42, row);
		treesMapChunkTwentyFour[23]  = new NatureObject(startXPosition + 43, row);
		treesMapChunkTwentyFour[24]  = new NatureObject(startXPosition + 44, row);
		treesMapChunkTwentyFour[25]  = new NatureObject(startXPosition + 45, row);
		treesMapChunkTwentyFour[26]  = new NatureObject(startXPosition + 46, row);
		treesMapChunkTwentyFour[27]  = new NatureObject(startXPosition + 47, row);
		treesMapChunkTwentyFour[28]  = new NatureObject(startXPosition + 48, row);
		treesMapChunkTwentyFour[29]  = new NatureObject(startXPosition + 49, row);
		treesMapChunkTwentyFour[30]  = new NatureObject(startXPosition + 50, row);
		treesMapChunkTwentyFour[31]  = new NatureObject(startXPosition + 51, row);
		treesMapChunkTwentyFour[32]  = new NatureObject(startXPosition + 52, row);
		treesMapChunkTwentyFour[33]  = new NatureObject(startXPosition + 53, row);
		treesMapChunkTwentyFour[34]  = new NatureObject(startXPosition + 54, row);
		treesMapChunkTwentyFour[35]  = new NatureObject(startXPosition + 55, row);
		treesMapChunkTwentyFour[36]  = new NatureObject(startXPosition + 56, row);
		treesMapChunkTwentyFour[37]  = new NatureObject(startXPosition + 57, row);
		treesMapChunkTwentyFour[38]  = new NatureObject(startXPosition + 58, row);
		treesMapChunkTwentyFour[39]  = new NatureObject(startXPosition + 59, row);
		treesMapChunkTwentyFour[40]  = new NatureObject(startXPosition + 60, row);
		treesMapChunkTwentyFour[41]  = new NatureObject(startXPosition + 61, row);
		treesMapChunkTwentyFour[42]  = new NatureObject(startXPosition + 62, row);
		treesMapChunkTwentyFour[43]  = new NatureObject(startXPosition + 63, row);
		treesMapChunkTwentyFour[44]  = new NatureObject(startXPosition + 64, row);
		treesMapChunkTwentyFour[45]  = new NatureObject(startXPosition + 65, row);
		treesMapChunkTwentyFour[46]  = new NatureObject(startXPosition + 66, row);
		treesMapChunkTwentyFour[47]  = new NatureObject(startXPosition + 67, row);
		row 				          = rowThreeStartPosition + 1;
		treesMapChunkTwentyFour[48]  = new NatureObject(startXPosition + 3, row);
		treesMapChunkTwentyFour[49]  = new NatureObject(startXPosition + 4, row);
		treesMapChunkTwentyFour[50]  = new NatureObject(startXPosition + 5, row);
		treesMapChunkTwentyFour[51]  = new NatureObject(startXPosition + 6, row);
		treesMapChunkTwentyFour[52]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyFour[53]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyFour[54]  = new NatureObject(startXPosition + 45, row);
		row 			              = rowThreeStartPosition + 2;
		treesMapChunkTwentyFour[55]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyFour[56]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyFour[57]  = new NatureObject(startXPosition + 45, row);
		row 			              = rowThreeStartPosition + 3;
		treesMapChunkTwentyFour[58]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyFour[59]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyFour[60]  = new NatureObject(startXPosition + 45, row);
		row 				          = rowThreeStartPosition + 4;
		treesMapChunkTwentyFour[61]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyFour[62]  = new NatureObject(startXPosition + 21, row);
		treesMapChunkTwentyFour[63]  = new NatureObject(startXPosition + 22, row);
		treesMapChunkTwentyFour[64]  = new NatureObject(startXPosition + 23, row);
		treesMapChunkTwentyFour[65]  = new NatureObject(startXPosition + 24, row);
		treesMapChunkTwentyFour[66]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyFour[67]  = new NatureObject(startXPosition + 45, row);
		treesMapChunkTwentyFour[68]  = new NatureObject(startXPosition + 46, row);
		treesMapChunkTwentyFour[69]  = new NatureObject(startXPosition + 47, row);
		treesMapChunkTwentyFour[70]  = new NatureObject(startXPosition + 48, row);
		treesMapChunkTwentyFour[71]  = new NatureObject(startXPosition + 49, row);
		row 				          = rowThreeStartPosition + 8;
		treesMapChunkTwentyFour[72]  = new NatureObject(startXPosition, row);
		treesMapChunkTwentyFour[73]  = new NatureObject(startXPosition + 1, row);
		treesMapChunkTwentyFour[74]  = new NatureObject(startXPosition + 2, row);
		treesMapChunkTwentyFour[75]  = new NatureObject(startXPosition + 3, row);
		treesMapChunkTwentyFour[76]  = new NatureObject(startXPosition + 7, row);
		treesMapChunkTwentyFour[77]  = new NatureObject(startXPosition + 10, row);
		treesMapChunkTwentyFour[78]  = new NatureObject(startXPosition + 15, row);
		treesMapChunkTwentyFour[79]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyFour[80]  = new NatureObject(startXPosition + 25, row);
		treesMapChunkTwentyFour[81]  = new NatureObject(startXPosition + 30, row);
		treesMapChunkTwentyFour[82]  = new NatureObject(startXPosition + 35, row);
		treesMapChunkTwentyFour[83]  = new NatureObject(startXPosition + 50, row);
		treesMapChunkTwentyFour[84]  = new NatureObject(startXPosition + 51, row);
		treesMapChunkTwentyFour[85]  = new NatureObject(startXPosition + 52, row);
		treesMapChunkTwentyFour[86]  = new NatureObject(startXPosition + 53, row);
		treesMapChunkTwentyFour[87]  = new NatureObject(startXPosition + 63, row);
		treesMapChunkTwentyFour[88]  = new NatureObject(startXPosition + 64, row);
		treesMapChunkTwentyFour[89]  = new NatureObject(startXPosition + 65, row);
		row 				          = rowThreeStartPosition + 9;
		treesMapChunkTwentyFour[90]  = new NatureObject(startXPosition + 3, row);
		treesMapChunkTwentyFour[91]  = new NatureObject(startXPosition + 8, row);
		treesMapChunkTwentyFour[92]  = new NatureObject(startXPosition + 14, row);
		treesMapChunkTwentyFour[93]  = new NatureObject(startXPosition + 28, row);
		treesMapChunkTwentyFour[94]  = new NatureObject(startXPosition + 29, row);
		treesMapChunkTwentyFour[95]  = new NatureObject(startXPosition + 30, row);
		treesMapChunkTwentyFour[96]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyFour[97]  = new NatureObject(startXPosition + 41, row);
		treesMapChunkTwentyFour[98]  = new NatureObject(startXPosition + 50, row);
		treesMapChunkTwentyFour[99]  = new NatureObject(startXPosition + 60, row);
		row 				          = rowThreeStartPosition + 10;
		treesMapChunkTwentyFour[100] = new NatureObject(startXPosition, row);
		treesMapChunkTwentyFour[101] = new NatureObject(startXPosition + 4, row);
		treesMapChunkTwentyFour[102] = new NatureObject(startXPosition + 7, row);
		treesMapChunkTwentyFour[103] = new NatureObject(startXPosition + 10, row);
		treesMapChunkTwentyFour[104] = new NatureObject(startXPosition + 13, row);
		treesMapChunkTwentyFour[105] = new NatureObject(startXPosition + 37, row);
		treesMapChunkTwentyFour[106] = new NatureObject(startXPosition + 38, row);
		row 				          = rowThreeStartPosition + 19;
		treesMapChunkTwentyFour[107] = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyFour[108] = new NatureObject(startXPosition + 25, row);
		treesMapChunkTwentyFour[109] = new NatureObject(startXPosition + 30, row);
		treesMapChunkTwentyFour[110] = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyFour[111] = new NatureObject(startXPosition + 50, row);
		treesMapChunkTwentyFour[112] = new NatureObject(startXPosition + 67, row);
		row 				          = rowThreeStartPosition + 20;
		treesMapChunkTwentyFour[113] = new NatureObject(startXPosition + 67, row);
		row 				          = rowThreeStartPosition + 21;
		treesMapChunkTwentyFour[114] = new NatureObject(startXPosition + 67, row);
		row 				          = rowThreeStartPosition + 22;
		treesMapChunkTwentyFour[115] = new NatureObject(startXPosition + 67, row);
		row 				          = rowThreeStartPosition + 24;
		treesMapChunkTwentyFour[116] = new NatureObject(startXPosition + 5, row);
		treesMapChunkTwentyFour[117] = new NatureObject(startXPosition + 14, row);
		treesMapChunkTwentyFour[118] = new NatureObject(startXPosition + 26, row);
		treesMapChunkTwentyFour[119] = new NatureObject(startXPosition + 33, row);
		treesMapChunkTwentyFour[120] = new NatureObject(startXPosition + 64, row);
		treesMapChunkTwentyFour[121] = new NatureObject(startXPosition + 65, row);
		treesMapChunkTwentyFour[122] = new NatureObject(startXPosition + 66, row);
		treesMapChunkTwentyFour[123] = new NatureObject(startXPosition + 67, row);
		row 				          = rowThreeStartPosition + 34;
		treesMapChunkTwentyFour[124] = new NatureObject(startXPosition + 7, row);
		treesMapChunkTwentyFour[125] = new NatureObject(startXPosition + 15, row);
		treesMapChunkTwentyFour[126] = new NatureObject(startXPosition + 16, row);
		treesMapChunkTwentyFour[127] = new NatureObject(startXPosition + 24, row);
		treesMapChunkTwentyFour[128] = new NatureObject(startXPosition + 36, row);
		treesMapChunkTwentyFour[129] = new NatureObject(startXPosition + 46, row);
		treesMapChunkTwentyFour[130] = new NatureObject(startXPosition + 56, row);
		treesMapChunkTwentyFour[131] = new NatureObject(startXPosition + 66, row);
		row 				          = rowThreeStartPosition + 49;
		treesMapChunkTwentyFour[132] = new NatureObject(startXPosition + 7, row);
		treesMapChunkTwentyFour[133] = new NatureObject(startXPosition + 15, row);
		treesMapChunkTwentyFour[134] = new NatureObject(startXPosition + 16, row);
		treesMapChunkTwentyFour[135] = new NatureObject(startXPosition + 24, row);
		treesMapChunkTwentyFour[136] = new NatureObject(startXPosition + 36, row);
		treesMapChunkTwentyFour[137] = new NatureObject(startXPosition + 46, row);
		treesMapChunkTwentyFour[138] = new NatureObject(startXPosition + 56, row);
		treesMapChunkTwentyFour[139] = new NatureObject(startXPosition + 66, row);
		
		addGameObjectsToGameObjectArrayList();
	}
	
	@Override
	protected void addGameObjectsToGameObjectArrayList() {
		for (int i = 0; i < treesMapChunkTwentyFour.length; i++) {
			GameObjectLoader.gameObjectList.add(treesMapChunkTwentyFour[i]);
		}
	}
}
