package loaders.TreeLoaders;

import gameobjects.GameObject;
import gameobjects.stationarygameobjects.NatureObject;
import loaders.GameObjectLoader;

public class TreeLoaderMapChunkTwentyNine extends MapChunkTreeLoader {
	public GameObject[] treesMapChunkTwentyNine  = new NatureObject[140];
	
	@Override
	public void loadTrees() {
		startXPosition		         = chunkWidth * 4;
		row 				         = rowFourStartPosition;
		treesMapChunkTwentyNine[0]   = new NatureObject(startXPosition, row);
		treesMapChunkTwentyNine[1]   = new NatureObject(startXPosition + 1, row);
		treesMapChunkTwentyNine[2]   = new NatureObject(startXPosition + 2, row);
		treesMapChunkTwentyNine[3]   = new NatureObject(startXPosition + 3, row);
		treesMapChunkTwentyNine[4]   = new NatureObject(startXPosition + 4, row);
		treesMapChunkTwentyNine[5]   = new NatureObject(startXPosition + 5, row);
		treesMapChunkTwentyNine[6]   = new NatureObject(startXPosition + 6, row);
		treesMapChunkTwentyNine[7]   = new NatureObject(startXPosition + 7, row);
		treesMapChunkTwentyNine[8]   = new NatureObject(startXPosition + 8, row);
		treesMapChunkTwentyNine[9]   = new NatureObject(startXPosition + 9, row);
		treesMapChunkTwentyNine[10]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyNine[11]  = new NatureObject(startXPosition + 21, row);
		treesMapChunkTwentyNine[12]  = new NatureObject(startXPosition + 22, row);
		treesMapChunkTwentyNine[13]  = new NatureObject(startXPosition + 23, row);
		treesMapChunkTwentyNine[14]  = new NatureObject(startXPosition + 24, row);
		treesMapChunkTwentyNine[15]  = new NatureObject(startXPosition + 25, row);
		treesMapChunkTwentyNine[16]  = new NatureObject(startXPosition + 26, row);
		treesMapChunkTwentyNine[17]  = new NatureObject(startXPosition + 27, row);
		treesMapChunkTwentyNine[18]  = new NatureObject(startXPosition + 28, row);
		treesMapChunkTwentyNine[19]  = new NatureObject(startXPosition + 29, row);
		treesMapChunkTwentyNine[20]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyNine[21]  = new NatureObject(startXPosition + 41, row);
		treesMapChunkTwentyNine[22]  = new NatureObject(startXPosition + 42, row);
		treesMapChunkTwentyNine[23]  = new NatureObject(startXPosition + 43, row);
		treesMapChunkTwentyNine[24]  = new NatureObject(startXPosition + 44, row);
		treesMapChunkTwentyNine[25]  = new NatureObject(startXPosition + 45, row);
		treesMapChunkTwentyNine[26]  = new NatureObject(startXPosition + 46, row);
		treesMapChunkTwentyNine[27]  = new NatureObject(startXPosition + 47, row);
		treesMapChunkTwentyNine[28]  = new NatureObject(startXPosition + 48, row);
		treesMapChunkTwentyNine[29]  = new NatureObject(startXPosition + 49, row);
		treesMapChunkTwentyNine[30]  = new NatureObject(startXPosition + 50, row);
		treesMapChunkTwentyNine[31]  = new NatureObject(startXPosition + 51, row);
		treesMapChunkTwentyNine[32]  = new NatureObject(startXPosition + 52, row);
		treesMapChunkTwentyNine[33]  = new NatureObject(startXPosition + 53, row);
		treesMapChunkTwentyNine[34]  = new NatureObject(startXPosition + 54, row);
		treesMapChunkTwentyNine[35]  = new NatureObject(startXPosition + 55, row);
		treesMapChunkTwentyNine[36]  = new NatureObject(startXPosition + 56, row);
		treesMapChunkTwentyNine[37]  = new NatureObject(startXPosition + 57, row);
		treesMapChunkTwentyNine[38]  = new NatureObject(startXPosition + 58, row);
		treesMapChunkTwentyNine[39]  = new NatureObject(startXPosition + 59, row);
		treesMapChunkTwentyNine[40]  = new NatureObject(startXPosition + 60, row);
		treesMapChunkTwentyNine[41]  = new NatureObject(startXPosition + 61, row);
		treesMapChunkTwentyNine[42]  = new NatureObject(startXPosition + 62, row);
		treesMapChunkTwentyNine[43]  = new NatureObject(startXPosition + 63, row);
		treesMapChunkTwentyNine[44]  = new NatureObject(startXPosition + 64, row);
		treesMapChunkTwentyNine[45]  = new NatureObject(startXPosition + 65, row);
		treesMapChunkTwentyNine[46]  = new NatureObject(startXPosition + 66, row);
		treesMapChunkTwentyNine[47]  = new NatureObject(startXPosition + 67, row);
		row 				          = rowFourStartPosition + 1;
		treesMapChunkTwentyNine[48]  = new NatureObject(startXPosition + 3, row);
		treesMapChunkTwentyNine[49]  = new NatureObject(startXPosition + 4, row);
		treesMapChunkTwentyNine[50]  = new NatureObject(startXPosition + 5, row);
		treesMapChunkTwentyNine[51]  = new NatureObject(startXPosition + 6, row);
		treesMapChunkTwentyNine[52]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyNine[53]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyNine[54]  = new NatureObject(startXPosition + 45, row);
		row 			              = rowFourStartPosition + 2;
		treesMapChunkTwentyNine[55]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyNine[56]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyNine[57]  = new NatureObject(startXPosition + 45, row);
		row 			              = rowFourStartPosition + 3;
		treesMapChunkTwentyNine[58]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyNine[59]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyNine[60]  = new NatureObject(startXPosition + 45, row);
		row 				          = rowFourStartPosition + 4;
		treesMapChunkTwentyNine[61]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyNine[62]  = new NatureObject(startXPosition + 21, row);
		treesMapChunkTwentyNine[63]  = new NatureObject(startXPosition + 22, row);
		treesMapChunkTwentyNine[64]  = new NatureObject(startXPosition + 23, row);
		treesMapChunkTwentyNine[65]  = new NatureObject(startXPosition + 24, row);
		treesMapChunkTwentyNine[66]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyNine[67]  = new NatureObject(startXPosition + 45, row);
		treesMapChunkTwentyNine[68]  = new NatureObject(startXPosition + 46, row);
		treesMapChunkTwentyNine[69]  = new NatureObject(startXPosition + 47, row);
		treesMapChunkTwentyNine[70]  = new NatureObject(startXPosition + 48, row);
		treesMapChunkTwentyNine[71]  = new NatureObject(startXPosition + 49, row);
		row 				          = rowFourStartPosition + 8;
		treesMapChunkTwentyNine[72]  = new NatureObject(startXPosition, row);
		treesMapChunkTwentyNine[73]  = new NatureObject(startXPosition + 1, row);
		treesMapChunkTwentyNine[74]  = new NatureObject(startXPosition + 2, row);
		treesMapChunkTwentyNine[75]  = new NatureObject(startXPosition + 3, row);
		treesMapChunkTwentyNine[76]  = new NatureObject(startXPosition + 7, row);
		treesMapChunkTwentyNine[77]  = new NatureObject(startXPosition + 10, row);
		treesMapChunkTwentyNine[78]  = new NatureObject(startXPosition + 15, row);
		treesMapChunkTwentyNine[79]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyNine[80]  = new NatureObject(startXPosition + 25, row);
		treesMapChunkTwentyNine[81]  = new NatureObject(startXPosition + 30, row);
		treesMapChunkTwentyNine[82]  = new NatureObject(startXPosition + 35, row);
		treesMapChunkTwentyNine[83]  = new NatureObject(startXPosition + 50, row);
		treesMapChunkTwentyNine[84]  = new NatureObject(startXPosition + 51, row);
		treesMapChunkTwentyNine[85]  = new NatureObject(startXPosition + 52, row);
		treesMapChunkTwentyNine[86]  = new NatureObject(startXPosition + 53, row);
		treesMapChunkTwentyNine[87]  = new NatureObject(startXPosition + 63, row);
		treesMapChunkTwentyNine[88]  = new NatureObject(startXPosition + 64, row);
		treesMapChunkTwentyNine[89]  = new NatureObject(startXPosition + 65, row);
		row 				          = rowFourStartPosition + 9;
		treesMapChunkTwentyNine[90]  = new NatureObject(startXPosition + 3, row);
		treesMapChunkTwentyNine[91]  = new NatureObject(startXPosition + 8, row);
		treesMapChunkTwentyNine[92]  = new NatureObject(startXPosition + 14, row);
		treesMapChunkTwentyNine[93]  = new NatureObject(startXPosition + 28, row);
		treesMapChunkTwentyNine[94]  = new NatureObject(startXPosition + 29, row);
		treesMapChunkTwentyNine[95]  = new NatureObject(startXPosition + 30, row);
		treesMapChunkTwentyNine[96]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyNine[97]  = new NatureObject(startXPosition + 41, row);
		treesMapChunkTwentyNine[98]  = new NatureObject(startXPosition + 50, row);
		treesMapChunkTwentyNine[99]  = new NatureObject(startXPosition + 60, row);
		row 				          = rowFourStartPosition + 10;
		treesMapChunkTwentyNine[100] = new NatureObject(startXPosition, row);
		treesMapChunkTwentyNine[101] = new NatureObject(startXPosition + 4, row);
		treesMapChunkTwentyNine[102] = new NatureObject(startXPosition + 7, row);
		treesMapChunkTwentyNine[103] = new NatureObject(startXPosition + 10, row);
		treesMapChunkTwentyNine[104] = new NatureObject(startXPosition + 13, row);
		treesMapChunkTwentyNine[105] = new NatureObject(startXPosition + 37, row);
		treesMapChunkTwentyNine[106] = new NatureObject(startXPosition + 38, row);
		row 				          = rowFourStartPosition + 19;
		treesMapChunkTwentyNine[107] = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyNine[108] = new NatureObject(startXPosition + 25, row);
		treesMapChunkTwentyNine[109] = new NatureObject(startXPosition + 30, row);
		treesMapChunkTwentyNine[110] = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyNine[111] = new NatureObject(startXPosition + 50, row);
		treesMapChunkTwentyNine[112] = new NatureObject(startXPosition + 67, row);
		row 				          = rowFourStartPosition + 20;
		treesMapChunkTwentyNine[113] = new NatureObject(startXPosition + 67, row);
		row 				          = rowFourStartPosition + 21;
		treesMapChunkTwentyNine[114] = new NatureObject(startXPosition + 67, row);
		row 				          = rowFourStartPosition + 22;
		treesMapChunkTwentyNine[115] = new NatureObject(startXPosition + 67, row);
		row 				          = rowFourStartPosition + 24;
		treesMapChunkTwentyNine[116] = new NatureObject(startXPosition + 5, row);
		treesMapChunkTwentyNine[117] = new NatureObject(startXPosition + 14, row);
		treesMapChunkTwentyNine[118] = new NatureObject(startXPosition + 26, row);
		treesMapChunkTwentyNine[119] = new NatureObject(startXPosition + 33, row);
		treesMapChunkTwentyNine[120] = new NatureObject(startXPosition + 64, row);
		treesMapChunkTwentyNine[121] = new NatureObject(startXPosition + 65, row);
		treesMapChunkTwentyNine[122] = new NatureObject(startXPosition + 66, row);
		treesMapChunkTwentyNine[123] = new NatureObject(startXPosition + 67, row);
		row 				          = rowFourStartPosition + 34;
		treesMapChunkTwentyNine[124] = new NatureObject(startXPosition + 7, row);
		treesMapChunkTwentyNine[125] = new NatureObject(startXPosition + 15, row);
		treesMapChunkTwentyNine[126] = new NatureObject(startXPosition + 16, row);
		treesMapChunkTwentyNine[127] = new NatureObject(startXPosition + 24, row);
		treesMapChunkTwentyNine[128] = new NatureObject(startXPosition + 36, row);
		treesMapChunkTwentyNine[129] = new NatureObject(startXPosition + 46, row);
		treesMapChunkTwentyNine[130] = new NatureObject(startXPosition + 56, row);
		treesMapChunkTwentyNine[131] = new NatureObject(startXPosition + 66, row);
		row 				          = rowFourStartPosition + 49;
		treesMapChunkTwentyNine[132] = new NatureObject(startXPosition + 7, row);
		treesMapChunkTwentyNine[133] = new NatureObject(startXPosition + 15, row);
		treesMapChunkTwentyNine[134] = new NatureObject(startXPosition + 16, row);
		treesMapChunkTwentyNine[135] = new NatureObject(startXPosition + 24, row);
		treesMapChunkTwentyNine[136] = new NatureObject(startXPosition + 36, row);
		treesMapChunkTwentyNine[137] = new NatureObject(startXPosition + 46, row);
		treesMapChunkTwentyNine[138] = new NatureObject(startXPosition + 56, row);
		treesMapChunkTwentyNine[139] = new NatureObject(startXPosition + 66, row);
		
		addGameObjectsToGameObjectArrayList();
	}
	
	@Override
	protected void addGameObjectsToGameObjectArrayList() {
		for (int i = 0; i < treesMapChunkTwentyNine.length; i++) {
			GameObjectLoader.gameObjectList.add(treesMapChunkTwentyNine[i]);
		}
	}
}
