package loaders.TreeLoaders;

import gameobjects.GameObject;
import gameobjects.stationarygameobjects.NatureObject;
import loaders.GameObjectLoader;

public class TreeLoaderMapChunkTwentyThree extends MapChunkTreeLoader {
	public GameObject[] treesMapChunkTwentyThree = new NatureObject[140];
	
	@Override
	public void loadTrees() {
		startXPosition		          = chunkWidth * 6;
		row 				          = rowThreeStartPosition;
		treesMapChunkTwentyThree[0]   = new NatureObject(startXPosition, row);
		treesMapChunkTwentyThree[1]   = new NatureObject(startXPosition + 1, row);
		treesMapChunkTwentyThree[2]   = new NatureObject(startXPosition + 2, row);
		treesMapChunkTwentyThree[3]   = new NatureObject(startXPosition + 3, row);
		treesMapChunkTwentyThree[4]   = new NatureObject(startXPosition + 4, row);
		treesMapChunkTwentyThree[5]   = new NatureObject(startXPosition + 5, row);
		treesMapChunkTwentyThree[6]   = new NatureObject(startXPosition + 6, row);
		treesMapChunkTwentyThree[7]   = new NatureObject(startXPosition + 7, row);
		treesMapChunkTwentyThree[8]   = new NatureObject(startXPosition + 8, row);
		treesMapChunkTwentyThree[9]   = new NatureObject(startXPosition + 9, row);
		treesMapChunkTwentyThree[10]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyThree[11]  = new NatureObject(startXPosition + 21, row);
		treesMapChunkTwentyThree[12]  = new NatureObject(startXPosition + 22, row);
		treesMapChunkTwentyThree[13]  = new NatureObject(startXPosition + 23, row);
		treesMapChunkTwentyThree[14]  = new NatureObject(startXPosition + 24, row);
		treesMapChunkTwentyThree[15]  = new NatureObject(startXPosition + 25, row);
		treesMapChunkTwentyThree[16]  = new NatureObject(startXPosition + 26, row);
		treesMapChunkTwentyThree[17]  = new NatureObject(startXPosition + 27, row);
		treesMapChunkTwentyThree[18]  = new NatureObject(startXPosition + 28, row);
		treesMapChunkTwentyThree[19]  = new NatureObject(startXPosition + 29, row);
		treesMapChunkTwentyThree[20]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyThree[21]  = new NatureObject(startXPosition + 41, row);
		treesMapChunkTwentyThree[22]  = new NatureObject(startXPosition + 42, row);
		treesMapChunkTwentyThree[23]  = new NatureObject(startXPosition + 43, row);
		treesMapChunkTwentyThree[24]  = new NatureObject(startXPosition + 44, row);
		treesMapChunkTwentyThree[25]  = new NatureObject(startXPosition + 45, row);
		treesMapChunkTwentyThree[26]  = new NatureObject(startXPosition + 46, row);
		treesMapChunkTwentyThree[27]  = new NatureObject(startXPosition + 47, row);
		treesMapChunkTwentyThree[28]  = new NatureObject(startXPosition + 48, row);
		treesMapChunkTwentyThree[29]  = new NatureObject(startXPosition + 49, row);
		treesMapChunkTwentyThree[30]  = new NatureObject(startXPosition + 50, row);
		treesMapChunkTwentyThree[31]  = new NatureObject(startXPosition + 51, row);
		treesMapChunkTwentyThree[32]  = new NatureObject(startXPosition + 52, row);
		treesMapChunkTwentyThree[33]  = new NatureObject(startXPosition + 53, row);
		treesMapChunkTwentyThree[34]  = new NatureObject(startXPosition + 54, row);
		treesMapChunkTwentyThree[35]  = new NatureObject(startXPosition + 55, row);
		treesMapChunkTwentyThree[36]  = new NatureObject(startXPosition + 56, row);
		treesMapChunkTwentyThree[37]  = new NatureObject(startXPosition + 57, row);
		treesMapChunkTwentyThree[38]  = new NatureObject(startXPosition + 58, row);
		treesMapChunkTwentyThree[39]  = new NatureObject(startXPosition + 59, row);
		treesMapChunkTwentyThree[40]  = new NatureObject(startXPosition + 60, row);
		treesMapChunkTwentyThree[41]  = new NatureObject(startXPosition + 61, row);
		treesMapChunkTwentyThree[42]  = new NatureObject(startXPosition + 62, row);
		treesMapChunkTwentyThree[43]  = new NatureObject(startXPosition + 63, row);
		treesMapChunkTwentyThree[44]  = new NatureObject(startXPosition + 64, row);
		treesMapChunkTwentyThree[45]  = new NatureObject(startXPosition + 65, row);
		treesMapChunkTwentyThree[46]  = new NatureObject(startXPosition + 66, row);
		treesMapChunkTwentyThree[47]  = new NatureObject(startXPosition + 67, row);
		row 				          = rowThreeStartPosition + 1;
		treesMapChunkTwentyThree[48]  = new NatureObject(startXPosition + 3, row);
		treesMapChunkTwentyThree[49]  = new NatureObject(startXPosition + 4, row);
		treesMapChunkTwentyThree[50]  = new NatureObject(startXPosition + 5, row);
		treesMapChunkTwentyThree[51]  = new NatureObject(startXPosition + 6, row);
		treesMapChunkTwentyThree[52]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyThree[53]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyThree[54]  = new NatureObject(startXPosition + 45, row);
		row 			              = rowThreeStartPosition + 2;
		treesMapChunkTwentyThree[55]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyThree[56]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyThree[57]  = new NatureObject(startXPosition + 45, row);
		row 			              = rowThreeStartPosition + 3;
		treesMapChunkTwentyThree[58]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyThree[59]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyThree[60]  = new NatureObject(startXPosition + 45, row);
		row 				          = rowThreeStartPosition + 4;
		treesMapChunkTwentyThree[61]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyThree[62]  = new NatureObject(startXPosition + 21, row);
		treesMapChunkTwentyThree[63]  = new NatureObject(startXPosition + 22, row);
		treesMapChunkTwentyThree[64]  = new NatureObject(startXPosition + 23, row);
		treesMapChunkTwentyThree[65]  = new NatureObject(startXPosition + 24, row);
		treesMapChunkTwentyThree[66]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyThree[67]  = new NatureObject(startXPosition + 45, row);
		treesMapChunkTwentyThree[68]  = new NatureObject(startXPosition + 46, row);
		treesMapChunkTwentyThree[69]  = new NatureObject(startXPosition + 47, row);
		treesMapChunkTwentyThree[70]  = new NatureObject(startXPosition + 48, row);
		treesMapChunkTwentyThree[71]  = new NatureObject(startXPosition + 49, row);
		row 				          = rowThreeStartPosition + 8;
		treesMapChunkTwentyThree[72]  = new NatureObject(startXPosition, row);
		treesMapChunkTwentyThree[73]  = new NatureObject(startXPosition + 1, row);
		treesMapChunkTwentyThree[74]  = new NatureObject(startXPosition + 2, row);
		treesMapChunkTwentyThree[75]  = new NatureObject(startXPosition + 3, row);
		treesMapChunkTwentyThree[76]  = new NatureObject(startXPosition + 7, row);
		treesMapChunkTwentyThree[77]  = new NatureObject(startXPosition + 10, row);
		treesMapChunkTwentyThree[78]  = new NatureObject(startXPosition + 15, row);
		treesMapChunkTwentyThree[79]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyThree[80]  = new NatureObject(startXPosition + 25, row);
		treesMapChunkTwentyThree[81]  = new NatureObject(startXPosition + 30, row);
		treesMapChunkTwentyThree[82]  = new NatureObject(startXPosition + 35, row);
		treesMapChunkTwentyThree[83]  = new NatureObject(startXPosition + 50, row);
		treesMapChunkTwentyThree[84]  = new NatureObject(startXPosition + 51, row);
		treesMapChunkTwentyThree[85]  = new NatureObject(startXPosition + 52, row);
		treesMapChunkTwentyThree[86]  = new NatureObject(startXPosition + 53, row);
		treesMapChunkTwentyThree[87]  = new NatureObject(startXPosition + 63, row);
		treesMapChunkTwentyThree[88]  = new NatureObject(startXPosition + 64, row);
		treesMapChunkTwentyThree[89]  = new NatureObject(startXPosition + 65, row);
		row 				          = rowThreeStartPosition + 9;
		treesMapChunkTwentyThree[90]  = new NatureObject(startXPosition + 3, row);
		treesMapChunkTwentyThree[91]  = new NatureObject(startXPosition + 8, row);
		treesMapChunkTwentyThree[92]  = new NatureObject(startXPosition + 14, row);
		treesMapChunkTwentyThree[93]  = new NatureObject(startXPosition + 28, row);
		treesMapChunkTwentyThree[94]  = new NatureObject(startXPosition + 29, row);
		treesMapChunkTwentyThree[95]  = new NatureObject(startXPosition + 30, row);
		treesMapChunkTwentyThree[96]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyThree[97]  = new NatureObject(startXPosition + 41, row);
		treesMapChunkTwentyThree[98]  = new NatureObject(startXPosition + 50, row);
		treesMapChunkTwentyThree[99]  = new NatureObject(startXPosition + 60, row);
		row 				          = rowThreeStartPosition + 10;
		treesMapChunkTwentyThree[100] = new NatureObject(startXPosition, row);
		treesMapChunkTwentyThree[101] = new NatureObject(startXPosition + 4, row);
		treesMapChunkTwentyThree[102] = new NatureObject(startXPosition + 7, row);
		treesMapChunkTwentyThree[103] = new NatureObject(startXPosition + 10, row);
		treesMapChunkTwentyThree[104] = new NatureObject(startXPosition + 13, row);
		treesMapChunkTwentyThree[105] = new NatureObject(startXPosition + 37, row);
		treesMapChunkTwentyThree[106] = new NatureObject(startXPosition + 38, row);
		row 				          = rowThreeStartPosition + 19;
		treesMapChunkTwentyThree[107] = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyThree[108] = new NatureObject(startXPosition + 25, row);
		treesMapChunkTwentyThree[109] = new NatureObject(startXPosition + 30, row);
		treesMapChunkTwentyThree[110] = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyThree[111] = new NatureObject(startXPosition + 50, row);
		treesMapChunkTwentyThree[112] = new NatureObject(startXPosition + 67, row);
		row 				          = rowThreeStartPosition + 20;
		treesMapChunkTwentyThree[113] = new NatureObject(startXPosition + 67, row);
		row 				          = rowThreeStartPosition + 21;
		treesMapChunkTwentyThree[114] = new NatureObject(startXPosition + 67, row);
		row 				          = rowThreeStartPosition + 22;
		treesMapChunkTwentyThree[115] = new NatureObject(startXPosition + 67, row);
		row 				          = rowThreeStartPosition + 24;
		treesMapChunkTwentyThree[116] = new NatureObject(startXPosition + 5, row);
		treesMapChunkTwentyThree[117] = new NatureObject(startXPosition + 14, row);
		treesMapChunkTwentyThree[118] = new NatureObject(startXPosition + 26, row);
		treesMapChunkTwentyThree[119] = new NatureObject(startXPosition + 33, row);
		treesMapChunkTwentyThree[120] = new NatureObject(startXPosition + 64, row);
		treesMapChunkTwentyThree[121] = new NatureObject(startXPosition + 65, row);
		treesMapChunkTwentyThree[122] = new NatureObject(startXPosition + 66, row);
		treesMapChunkTwentyThree[123] = new NatureObject(startXPosition + 67, row);
		row 				          = rowThreeStartPosition + 34;
		treesMapChunkTwentyThree[124] = new NatureObject(startXPosition + 7, row);
		treesMapChunkTwentyThree[125] = new NatureObject(startXPosition + 15, row);
		treesMapChunkTwentyThree[126] = new NatureObject(startXPosition + 16, row);
		treesMapChunkTwentyThree[127] = new NatureObject(startXPosition + 24, row);
		treesMapChunkTwentyThree[128] = new NatureObject(startXPosition + 36, row);
		treesMapChunkTwentyThree[129] = new NatureObject(startXPosition + 46, row);
		treesMapChunkTwentyThree[130] = new NatureObject(startXPosition + 56, row);
		treesMapChunkTwentyThree[131] = new NatureObject(startXPosition + 66, row);
		row 				          = rowThreeStartPosition + 49;
		treesMapChunkTwentyThree[132] = new NatureObject(startXPosition + 7, row);
		treesMapChunkTwentyThree[133] = new NatureObject(startXPosition + 15, row);
		treesMapChunkTwentyThree[134] = new NatureObject(startXPosition + 16, row);
		treesMapChunkTwentyThree[135] = new NatureObject(startXPosition + 24, row);
		treesMapChunkTwentyThree[136] = new NatureObject(startXPosition + 36, row);
		treesMapChunkTwentyThree[137] = new NatureObject(startXPosition + 46, row);
		treesMapChunkTwentyThree[138] = new NatureObject(startXPosition + 56, row);
		treesMapChunkTwentyThree[139] = new NatureObject(startXPosition + 66, row);
		
		addGameObjectsToGameObjectArrayList();
	}

	@Override
	protected void addGameObjectsToGameObjectArrayList() {
		for (int i = 0; i < treesMapChunkTwentyThree.length; i++) {
			GameObjectLoader.gameObjectList.add(treesMapChunkTwentyThree[i]);
		}
	}
}
