package loaders.TreeLoaders;

import gameobjects.GameObject;
import gameobjects.stationarygameobjects.NatureObject;
import loaders.GameObjectLoader;

public class TreeLoaderMapChunkThirty extends MapChunkTreeLoader {
	public GameObject[] treesMapChunkThirty = new NatureObject[140];
	
	@Override
	public void loadTrees() {
		startXPosition		         = chunkWidth * 5;
		row 				         = rowFourStartPosition;
		treesMapChunkThirty[0]   = new NatureObject(startXPosition, row);
		treesMapChunkThirty[1]   = new NatureObject(startXPosition + 1, row);
		treesMapChunkThirty[2]   = new NatureObject(startXPosition + 2, row);
		treesMapChunkThirty[3]   = new NatureObject(startXPosition + 3, row);
		treesMapChunkThirty[4]   = new NatureObject(startXPosition + 4, row);
		treesMapChunkThirty[5]   = new NatureObject(startXPosition + 5, row);
		treesMapChunkThirty[6]   = new NatureObject(startXPosition + 6, row);
		treesMapChunkThirty[7]   = new NatureObject(startXPosition + 7, row);
		treesMapChunkThirty[8]   = new NatureObject(startXPosition + 8, row);
		treesMapChunkThirty[9]   = new NatureObject(startXPosition + 9, row);
		treesMapChunkThirty[10]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkThirty[11]  = new NatureObject(startXPosition + 21, row);
		treesMapChunkThirty[12]  = new NatureObject(startXPosition + 22, row);
		treesMapChunkThirty[13]  = new NatureObject(startXPosition + 23, row);
		treesMapChunkThirty[14]  = new NatureObject(startXPosition + 24, row);
		treesMapChunkThirty[15]  = new NatureObject(startXPosition + 25, row);
		treesMapChunkThirty[16]  = new NatureObject(startXPosition + 26, row);
		treesMapChunkThirty[17]  = new NatureObject(startXPosition + 27, row);
		treesMapChunkThirty[18]  = new NatureObject(startXPosition + 28, row);
		treesMapChunkThirty[19]  = new NatureObject(startXPosition + 29, row);
		treesMapChunkThirty[20]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkThirty[21]  = new NatureObject(startXPosition + 41, row);
		treesMapChunkThirty[22]  = new NatureObject(startXPosition + 42, row);
		treesMapChunkThirty[23]  = new NatureObject(startXPosition + 43, row);
		treesMapChunkThirty[24]  = new NatureObject(startXPosition + 44, row);
		treesMapChunkThirty[25]  = new NatureObject(startXPosition + 45, row);
		treesMapChunkThirty[26]  = new NatureObject(startXPosition + 46, row);
		treesMapChunkThirty[27]  = new NatureObject(startXPosition + 47, row);
		treesMapChunkThirty[28]  = new NatureObject(startXPosition + 48, row);
		treesMapChunkThirty[29]  = new NatureObject(startXPosition + 49, row);
		treesMapChunkThirty[30]  = new NatureObject(startXPosition + 50, row);
		treesMapChunkThirty[31]  = new NatureObject(startXPosition + 51, row);
		treesMapChunkThirty[32]  = new NatureObject(startXPosition + 52, row);
		treesMapChunkThirty[33]  = new NatureObject(startXPosition + 53, row);
		treesMapChunkThirty[34]  = new NatureObject(startXPosition + 54, row);
		treesMapChunkThirty[35]  = new NatureObject(startXPosition + 55, row);
		treesMapChunkThirty[36]  = new NatureObject(startXPosition + 56, row);
		treesMapChunkThirty[37]  = new NatureObject(startXPosition + 57, row);
		treesMapChunkThirty[38]  = new NatureObject(startXPosition + 58, row);
		treesMapChunkThirty[39]  = new NatureObject(startXPosition + 59, row);
		treesMapChunkThirty[40]  = new NatureObject(startXPosition + 60, row);
		treesMapChunkThirty[41]  = new NatureObject(startXPosition + 61, row);
		treesMapChunkThirty[42]  = new NatureObject(startXPosition + 62, row);
		treesMapChunkThirty[43]  = new NatureObject(startXPosition + 63, row);
		treesMapChunkThirty[44]  = new NatureObject(startXPosition + 64, row);
		treesMapChunkThirty[45]  = new NatureObject(startXPosition + 65, row);
		treesMapChunkThirty[46]  = new NatureObject(startXPosition + 66, row);
		treesMapChunkThirty[47]  = new NatureObject(startXPosition + 67, row);
		row 				          = rowFourStartPosition + 1;
		treesMapChunkThirty[48]  = new NatureObject(startXPosition + 3, row);
		treesMapChunkThirty[49]  = new NatureObject(startXPosition + 4, row);
		treesMapChunkThirty[50]  = new NatureObject(startXPosition + 5, row);
		treesMapChunkThirty[51]  = new NatureObject(startXPosition + 6, row);
		treesMapChunkThirty[52]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkThirty[53]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkThirty[54]  = new NatureObject(startXPosition + 45, row);
		row 			              = rowFourStartPosition + 2;
		treesMapChunkThirty[55]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkThirty[56]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkThirty[57]  = new NatureObject(startXPosition + 45, row);
		row 			              = rowFourStartPosition + 3;
		treesMapChunkThirty[58]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkThirty[59]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkThirty[60]  = new NatureObject(startXPosition + 45, row);
		row 				          = rowFourStartPosition + 4;
		treesMapChunkThirty[61]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkThirty[62]  = new NatureObject(startXPosition + 21, row);
		treesMapChunkThirty[63]  = new NatureObject(startXPosition + 22, row);
		treesMapChunkThirty[64]  = new NatureObject(startXPosition + 23, row);
		treesMapChunkThirty[65]  = new NatureObject(startXPosition + 24, row);
		treesMapChunkThirty[66]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkThirty[67]  = new NatureObject(startXPosition + 45, row);
		treesMapChunkThirty[68]  = new NatureObject(startXPosition + 46, row);
		treesMapChunkThirty[69]  = new NatureObject(startXPosition + 47, row);
		treesMapChunkThirty[70]  = new NatureObject(startXPosition + 48, row);
		treesMapChunkThirty[71]  = new NatureObject(startXPosition + 49, row);
		row 				          = rowFourStartPosition + 8;
		treesMapChunkThirty[72]  = new NatureObject(startXPosition, row);
		treesMapChunkThirty[73]  = new NatureObject(startXPosition + 1, row);
		treesMapChunkThirty[74]  = new NatureObject(startXPosition + 2, row);
		treesMapChunkThirty[75]  = new NatureObject(startXPosition + 3, row);
		treesMapChunkThirty[76]  = new NatureObject(startXPosition + 7, row);
		treesMapChunkThirty[77]  = new NatureObject(startXPosition + 10, row);
		treesMapChunkThirty[78]  = new NatureObject(startXPosition + 15, row);
		treesMapChunkThirty[79]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkThirty[80]  = new NatureObject(startXPosition + 25, row);
		treesMapChunkThirty[81]  = new NatureObject(startXPosition + 30, row);
		treesMapChunkThirty[82]  = new NatureObject(startXPosition + 35, row);
		treesMapChunkThirty[83]  = new NatureObject(startXPosition + 50, row);
		treesMapChunkThirty[84]  = new NatureObject(startXPosition + 51, row);
		treesMapChunkThirty[85]  = new NatureObject(startXPosition + 52, row);
		treesMapChunkThirty[86]  = new NatureObject(startXPosition + 53, row);
		treesMapChunkThirty[87]  = new NatureObject(startXPosition + 63, row);
		treesMapChunkThirty[88]  = new NatureObject(startXPosition + 64, row);
		treesMapChunkThirty[89]  = new NatureObject(startXPosition + 65, row);
		row 				          = rowFourStartPosition + 9;
		treesMapChunkThirty[90]  = new NatureObject(startXPosition + 3, row);
		treesMapChunkThirty[91]  = new NatureObject(startXPosition + 8, row);
		treesMapChunkThirty[92]  = new NatureObject(startXPosition + 14, row);
		treesMapChunkThirty[93]  = new NatureObject(startXPosition + 28, row);
		treesMapChunkThirty[94]  = new NatureObject(startXPosition + 29, row);
		treesMapChunkThirty[95]  = new NatureObject(startXPosition + 30, row);
		treesMapChunkThirty[96]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkThirty[97]  = new NatureObject(startXPosition + 41, row);
		treesMapChunkThirty[98]  = new NatureObject(startXPosition + 50, row);
		treesMapChunkThirty[99]  = new NatureObject(startXPosition + 60, row);
		row 				          = rowFourStartPosition + 10;
		treesMapChunkThirty[100] = new NatureObject(startXPosition, row);
		treesMapChunkThirty[101] = new NatureObject(startXPosition + 4, row);
		treesMapChunkThirty[102] = new NatureObject(startXPosition + 7, row);
		treesMapChunkThirty[103] = new NatureObject(startXPosition + 10, row);
		treesMapChunkThirty[104] = new NatureObject(startXPosition + 13, row);
		treesMapChunkThirty[105] = new NatureObject(startXPosition + 37, row);
		treesMapChunkThirty[106] = new NatureObject(startXPosition + 38, row);
		row 				          = rowFourStartPosition + 19;
		treesMapChunkThirty[107] = new NatureObject(startXPosition + 20, row);
		treesMapChunkThirty[108] = new NatureObject(startXPosition + 25, row);
		treesMapChunkThirty[109] = new NatureObject(startXPosition + 30, row);
		treesMapChunkThirty[110] = new NatureObject(startXPosition + 40, row);
		treesMapChunkThirty[111] = new NatureObject(startXPosition + 50, row);
		treesMapChunkThirty[112] = new NatureObject(startXPosition + 67, row);
		row 				          = rowFourStartPosition + 20;
		treesMapChunkThirty[113] = new NatureObject(startXPosition + 67, row);
		row 				          = rowFourStartPosition + 21;
		treesMapChunkThirty[114] = new NatureObject(startXPosition + 67, row);
		row 				          = rowFourStartPosition + 22;
		treesMapChunkThirty[115] = new NatureObject(startXPosition + 67, row);
		row 				          = rowFourStartPosition + 24;
		treesMapChunkThirty[116] = new NatureObject(startXPosition + 5, row);
		treesMapChunkThirty[117] = new NatureObject(startXPosition + 14, row);
		treesMapChunkThirty[118] = new NatureObject(startXPosition + 26, row);
		treesMapChunkThirty[119] = new NatureObject(startXPosition + 33, row);
		treesMapChunkThirty[120] = new NatureObject(startXPosition + 64, row);
		treesMapChunkThirty[121] = new NatureObject(startXPosition + 65, row);
		treesMapChunkThirty[122] = new NatureObject(startXPosition + 66, row);
		treesMapChunkThirty[123] = new NatureObject(startXPosition + 67, row);
		row 				          = rowFourStartPosition + 34;
		treesMapChunkThirty[124] = new NatureObject(startXPosition + 7, row);
		treesMapChunkThirty[125] = new NatureObject(startXPosition + 15, row);
		treesMapChunkThirty[126] = new NatureObject(startXPosition + 16, row);
		treesMapChunkThirty[127] = new NatureObject(startXPosition + 24, row);
		treesMapChunkThirty[128] = new NatureObject(startXPosition + 36, row);
		treesMapChunkThirty[129] = new NatureObject(startXPosition + 46, row);
		treesMapChunkThirty[130] = new NatureObject(startXPosition + 56, row);
		treesMapChunkThirty[131] = new NatureObject(startXPosition + 66, row);
		row 				          = rowFourStartPosition + 49;
		treesMapChunkThirty[132] = new NatureObject(startXPosition + 7, row);
		treesMapChunkThirty[133] = new NatureObject(startXPosition + 15, row);
		treesMapChunkThirty[134] = new NatureObject(startXPosition + 16, row);
		treesMapChunkThirty[135] = new NatureObject(startXPosition + 24, row);
		treesMapChunkThirty[136] = new NatureObject(startXPosition + 36, row);
		treesMapChunkThirty[137] = new NatureObject(startXPosition + 46, row);
		treesMapChunkThirty[138] = new NatureObject(startXPosition + 56, row);
		treesMapChunkThirty[139] = new NatureObject(startXPosition + 66, row);
		
		addGameObjectsToGameObjectArrayList();
	}
	
	@Override
	protected void addGameObjectsToGameObjectArrayList() {
		for (int i = 0; i < treesMapChunkThirty.length; i++) {
			GameObjectLoader.gameObjectList.add(treesMapChunkThirty[i]);
		}
	}
}
