package loaders.TreeLoaders;

import gameobjects.GameObject;
import gameobjects.stationarygameobjects.NatureObject;
import loaders.GameObjectLoader;

public class TreeLoaderMapChunkThirtyOne extends MapChunkTreeLoader {
	
	public GameObject[] treesMapChunkThirtyOne = new NatureObject[140];
	
	@Override
	public void loadTrees() {
		startXPosition		        = chunkWidth * 6;
		row 				        = rowFourStartPosition;
		treesMapChunkThirtyOne[0]   = new NatureObject(startXPosition, row);
		treesMapChunkThirtyOne[1]   = new NatureObject(startXPosition + 1, row);
		treesMapChunkThirtyOne[2]   = new NatureObject(startXPosition + 2, row);
		treesMapChunkThirtyOne[3]   = new NatureObject(startXPosition + 3, row);
		treesMapChunkThirtyOne[4]   = new NatureObject(startXPosition + 4, row);
		treesMapChunkThirtyOne[5]   = new NatureObject(startXPosition + 5, row);
		treesMapChunkThirtyOne[6]   = new NatureObject(startXPosition + 6, row);
		treesMapChunkThirtyOne[7]   = new NatureObject(startXPosition + 7, row);
		treesMapChunkThirtyOne[8]   = new NatureObject(startXPosition + 8, row);
		treesMapChunkThirtyOne[9]   = new NatureObject(startXPosition + 9, row);
		treesMapChunkThirtyOne[10]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkThirtyOne[11]  = new NatureObject(startXPosition + 21, row);
		treesMapChunkThirtyOne[12]  = new NatureObject(startXPosition + 22, row);
		treesMapChunkThirtyOne[13]  = new NatureObject(startXPosition + 23, row);
		treesMapChunkThirtyOne[14]  = new NatureObject(startXPosition + 24, row);
		treesMapChunkThirtyOne[15]  = new NatureObject(startXPosition + 25, row);
		treesMapChunkThirtyOne[16]  = new NatureObject(startXPosition + 26, row);
		treesMapChunkThirtyOne[17]  = new NatureObject(startXPosition + 27, row);
		treesMapChunkThirtyOne[18]  = new NatureObject(startXPosition + 28, row);
		treesMapChunkThirtyOne[19]  = new NatureObject(startXPosition + 29, row);
		treesMapChunkThirtyOne[20]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkThirtyOne[21]  = new NatureObject(startXPosition + 41, row);
		treesMapChunkThirtyOne[22]  = new NatureObject(startXPosition + 42, row);
		treesMapChunkThirtyOne[23]  = new NatureObject(startXPosition + 43, row);
		treesMapChunkThirtyOne[24]  = new NatureObject(startXPosition + 44, row);
		treesMapChunkThirtyOne[25]  = new NatureObject(startXPosition + 45, row);
		treesMapChunkThirtyOne[26]  = new NatureObject(startXPosition + 46, row);
		treesMapChunkThirtyOne[27]  = new NatureObject(startXPosition + 47, row);
		treesMapChunkThirtyOne[28]  = new NatureObject(startXPosition + 48, row);
		treesMapChunkThirtyOne[29]  = new NatureObject(startXPosition + 49, row);
		treesMapChunkThirtyOne[30]  = new NatureObject(startXPosition + 50, row);
		treesMapChunkThirtyOne[31]  = new NatureObject(startXPosition + 51, row);
		treesMapChunkThirtyOne[32]  = new NatureObject(startXPosition + 52, row);
		treesMapChunkThirtyOne[33]  = new NatureObject(startXPosition + 53, row);
		treesMapChunkThirtyOne[34]  = new NatureObject(startXPosition + 54, row);
		treesMapChunkThirtyOne[35]  = new NatureObject(startXPosition + 55, row);
		treesMapChunkThirtyOne[36]  = new NatureObject(startXPosition + 56, row);
		treesMapChunkThirtyOne[37]  = new NatureObject(startXPosition + 57, row);
		treesMapChunkThirtyOne[38]  = new NatureObject(startXPosition + 58, row);
		treesMapChunkThirtyOne[39]  = new NatureObject(startXPosition + 59, row);
		treesMapChunkThirtyOne[40]  = new NatureObject(startXPosition + 60, row);
		treesMapChunkThirtyOne[41]  = new NatureObject(startXPosition + 61, row);
		treesMapChunkThirtyOne[42]  = new NatureObject(startXPosition + 62, row);
		treesMapChunkThirtyOne[43]  = new NatureObject(startXPosition + 63, row);
		treesMapChunkThirtyOne[44]  = new NatureObject(startXPosition + 64, row);
		treesMapChunkThirtyOne[45]  = new NatureObject(startXPosition + 65, row);
		treesMapChunkThirtyOne[46]  = new NatureObject(startXPosition + 66, row);
		treesMapChunkThirtyOne[47]  = new NatureObject(startXPosition + 67, row);
		row 				        = rowFourStartPosition + 1;
		treesMapChunkThirtyOne[48]  = new NatureObject(startXPosition + 3, row);
		treesMapChunkThirtyOne[49]  = new NatureObject(startXPosition + 4, row);
		treesMapChunkThirtyOne[50]  = new NatureObject(startXPosition + 5, row);
		treesMapChunkThirtyOne[51]  = new NatureObject(startXPosition + 6, row);
		treesMapChunkThirtyOne[52]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkThirtyOne[53]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkThirtyOne[54]  = new NatureObject(startXPosition + 45, row);
		row 			            = rowFourStartPosition + 2;
		treesMapChunkThirtyOne[55]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkThirtyOne[56]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkThirtyOne[57]  = new NatureObject(startXPosition + 45, row);
		row 			            = rowFourStartPosition + 3;
		treesMapChunkThirtyOne[58]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkThirtyOne[59]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkThirtyOne[60]  = new NatureObject(startXPosition + 45, row);
		row 				        = rowFourStartPosition + 4;
		treesMapChunkThirtyOne[61]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkThirtyOne[62]  = new NatureObject(startXPosition + 21, row);
		treesMapChunkThirtyOne[63]  = new NatureObject(startXPosition + 22, row);
		treesMapChunkThirtyOne[64]  = new NatureObject(startXPosition + 23, row);
		treesMapChunkThirtyOne[65]  = new NatureObject(startXPosition + 24, row);
		treesMapChunkThirtyOne[66]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkThirtyOne[67]  = new NatureObject(startXPosition + 45, row);
		treesMapChunkThirtyOne[68]  = new NatureObject(startXPosition + 46, row);
		treesMapChunkThirtyOne[69]  = new NatureObject(startXPosition + 47, row);
		treesMapChunkThirtyOne[70]  = new NatureObject(startXPosition + 48, row);
		treesMapChunkThirtyOne[71]  = new NatureObject(startXPosition + 49, row);
		row 				        = rowFourStartPosition + 8;
		treesMapChunkThirtyOne[72]  = new NatureObject(startXPosition, row);
		treesMapChunkThirtyOne[73]  = new NatureObject(startXPosition + 1, row);
		treesMapChunkThirtyOne[74]  = new NatureObject(startXPosition + 2, row);
		treesMapChunkThirtyOne[75]  = new NatureObject(startXPosition + 3, row);
		treesMapChunkThirtyOne[76]  = new NatureObject(startXPosition + 7, row);
		treesMapChunkThirtyOne[77]  = new NatureObject(startXPosition + 10, row);
		treesMapChunkThirtyOne[78]  = new NatureObject(startXPosition + 15, row);
		treesMapChunkThirtyOne[79]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkThirtyOne[80]  = new NatureObject(startXPosition + 25, row);
		treesMapChunkThirtyOne[81]  = new NatureObject(startXPosition + 30, row);
		treesMapChunkThirtyOne[82]  = new NatureObject(startXPosition + 35, row);
		treesMapChunkThirtyOne[83]  = new NatureObject(startXPosition + 50, row);
		treesMapChunkThirtyOne[84]  = new NatureObject(startXPosition + 51, row);
		treesMapChunkThirtyOne[85]  = new NatureObject(startXPosition + 52, row);
		treesMapChunkThirtyOne[86]  = new NatureObject(startXPosition + 53, row);
		treesMapChunkThirtyOne[87]  = new NatureObject(startXPosition + 63, row);
		treesMapChunkThirtyOne[88]  = new NatureObject(startXPosition + 64, row);
		treesMapChunkThirtyOne[89]  = new NatureObject(startXPosition + 65, row);
		row 				        = rowFourStartPosition + 9;
		treesMapChunkThirtyOne[90]  = new NatureObject(startXPosition + 3, row);
		treesMapChunkThirtyOne[91]  = new NatureObject(startXPosition + 8, row);
		treesMapChunkThirtyOne[92]  = new NatureObject(startXPosition + 14, row);
		treesMapChunkThirtyOne[93]  = new NatureObject(startXPosition + 28, row);
		treesMapChunkThirtyOne[94]  = new NatureObject(startXPosition + 29, row);
		treesMapChunkThirtyOne[95]  = new NatureObject(startXPosition + 30, row);
		treesMapChunkThirtyOne[96]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkThirtyOne[97]  = new NatureObject(startXPosition + 41, row);
		treesMapChunkThirtyOne[98]  = new NatureObject(startXPosition + 50, row);
		treesMapChunkThirtyOne[99]  = new NatureObject(startXPosition + 60, row);
		row 				        = rowFourStartPosition + 10;
		treesMapChunkThirtyOne[100] = new NatureObject(startXPosition, row);
		treesMapChunkThirtyOne[101] = new NatureObject(startXPosition + 4, row);
		treesMapChunkThirtyOne[102] = new NatureObject(startXPosition + 7, row);
		treesMapChunkThirtyOne[103] = new NatureObject(startXPosition + 10, row);
		treesMapChunkThirtyOne[104] = new NatureObject(startXPosition + 13, row);
		treesMapChunkThirtyOne[105] = new NatureObject(startXPosition + 37, row);
		treesMapChunkThirtyOne[106] = new NatureObject(startXPosition + 38, row);
		row 				        = rowFourStartPosition + 19;
		treesMapChunkThirtyOne[107] = new NatureObject(startXPosition + 20, row);
		treesMapChunkThirtyOne[108] = new NatureObject(startXPosition + 25, row);
		treesMapChunkThirtyOne[109] = new NatureObject(startXPosition + 30, row);
		treesMapChunkThirtyOne[110] = new NatureObject(startXPosition + 40, row);
		treesMapChunkThirtyOne[111] = new NatureObject(startXPosition + 50, row);
		treesMapChunkThirtyOne[112] = new NatureObject(startXPosition + 67, row);
		row 			            = rowFourStartPosition + 20;
		treesMapChunkThirtyOne[113] = new NatureObject(startXPosition + 67, row);
		row 				        = rowFourStartPosition + 21;
		treesMapChunkThirtyOne[114] = new NatureObject(startXPosition + 67, row);
		row 				        = rowFourStartPosition + 22;
		treesMapChunkThirtyOne[115] = new NatureObject(startXPosition + 67, row);
		row 				        = rowFourStartPosition + 24;
		treesMapChunkThirtyOne[116] = new NatureObject(startXPosition + 5, row);
		treesMapChunkThirtyOne[117] = new NatureObject(startXPosition + 14, row);
		treesMapChunkThirtyOne[118] = new NatureObject(startXPosition + 26, row);
		treesMapChunkThirtyOne[119] = new NatureObject(startXPosition + 33, row);
		treesMapChunkThirtyOne[120] = new NatureObject(startXPosition + 64, row);
		treesMapChunkThirtyOne[121] = new NatureObject(startXPosition + 65, row);
		treesMapChunkThirtyOne[122] = new NatureObject(startXPosition + 66, row);
		treesMapChunkThirtyOne[123] = new NatureObject(startXPosition + 67, row);
		row 				        = rowFourStartPosition + 34;
		treesMapChunkThirtyOne[124] = new NatureObject(startXPosition + 7, row);
		treesMapChunkThirtyOne[125] = new NatureObject(startXPosition + 15, row);
		treesMapChunkThirtyOne[126] = new NatureObject(startXPosition + 16, row);
		treesMapChunkThirtyOne[127] = new NatureObject(startXPosition + 24, row);
		treesMapChunkThirtyOne[128] = new NatureObject(startXPosition + 36, row);
		treesMapChunkThirtyOne[129] = new NatureObject(startXPosition + 46, row);
		treesMapChunkThirtyOne[130] = new NatureObject(startXPosition + 56, row);
		treesMapChunkThirtyOne[131] = new NatureObject(startXPosition + 66, row);
		row 				        = rowFourStartPosition + 49;
		treesMapChunkThirtyOne[132] = new NatureObject(startXPosition + 7, row);
		treesMapChunkThirtyOne[133] = new NatureObject(startXPosition + 15, row);
		treesMapChunkThirtyOne[134] = new NatureObject(startXPosition + 16, row);
		treesMapChunkThirtyOne[135] = new NatureObject(startXPosition + 24, row);
		treesMapChunkThirtyOne[136] = new NatureObject(startXPosition + 36, row);
		treesMapChunkThirtyOne[137] = new NatureObject(startXPosition + 46, row);
		treesMapChunkThirtyOne[138] = new NatureObject(startXPosition + 56, row);
		treesMapChunkThirtyOne[139] = new NatureObject(startXPosition + 66, row);
		
		addGameObjectsToGameObjectArrayList();
	}

	@Override
	protected void addGameObjectsToGameObjectArrayList() {
		for (int i = 0; i < treesMapChunkThirtyOne.length; i++) {
			GameObjectLoader.gameObjectList.add(treesMapChunkThirtyOne[i]);
		}
	}
}
