package loaders.TreeLoaders;

import gameobjects.GameObject;
import gameobjects.stationarygameobjects.NatureObject;
import loaders.GameObjectLoader;

public class TreeLoaderMapChunkTwentyTwo extends MapChunkTreeLoader {
	public GameObject[] treesMapChunkTwentyTwo   = new NatureObject[140];
	
	@Override
	public void loadTrees() {
		startXPosition		        = chunkWidth * 5;
		row 				        = rowThreeStartPosition;
		treesMapChunkTwentyTwo[0]   = new NatureObject(startXPosition, row);
		treesMapChunkTwentyTwo[1]   = new NatureObject(startXPosition + 1, row);
		treesMapChunkTwentyTwo[2]   = new NatureObject(startXPosition + 2, row);
		treesMapChunkTwentyTwo[3]   = new NatureObject(startXPosition + 3, row);
		treesMapChunkTwentyTwo[4]   = new NatureObject(startXPosition + 4, row);
		treesMapChunkTwentyTwo[5]   = new NatureObject(startXPosition + 5, row);
		treesMapChunkTwentyTwo[6]   = new NatureObject(startXPosition + 6, row);
		treesMapChunkTwentyTwo[7]   = new NatureObject(startXPosition + 7, row);
		treesMapChunkTwentyTwo[8]   = new NatureObject(startXPosition + 8, row);
		treesMapChunkTwentyTwo[9]   = new NatureObject(startXPosition + 9, row);
		treesMapChunkTwentyTwo[10]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyTwo[11]  = new NatureObject(startXPosition + 21, row);
		treesMapChunkTwentyTwo[12]  = new NatureObject(startXPosition + 22, row);
		treesMapChunkTwentyTwo[13]  = new NatureObject(startXPosition + 23, row);
		treesMapChunkTwentyTwo[14]  = new NatureObject(startXPosition + 24, row);
		treesMapChunkTwentyTwo[15]  = new NatureObject(startXPosition + 25, row);
		treesMapChunkTwentyTwo[16]  = new NatureObject(startXPosition + 26, row);
		treesMapChunkTwentyTwo[17]  = new NatureObject(startXPosition + 27, row);
		treesMapChunkTwentyTwo[18]  = new NatureObject(startXPosition + 28, row);
		treesMapChunkTwentyTwo[19]  = new NatureObject(startXPosition + 29, row);
		treesMapChunkTwentyTwo[20]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyTwo[21]  = new NatureObject(startXPosition + 41, row);
		treesMapChunkTwentyTwo[22]  = new NatureObject(startXPosition + 42, row);
		treesMapChunkTwentyTwo[23]  = new NatureObject(startXPosition + 43, row);
		treesMapChunkTwentyTwo[24]  = new NatureObject(startXPosition + 44, row);
		treesMapChunkTwentyTwo[25]  = new NatureObject(startXPosition + 45, row);
		treesMapChunkTwentyTwo[26]  = new NatureObject(startXPosition + 46, row);
		treesMapChunkTwentyTwo[27]  = new NatureObject(startXPosition + 47, row);
		treesMapChunkTwentyTwo[28]  = new NatureObject(startXPosition + 48, row);
		treesMapChunkTwentyTwo[29]  = new NatureObject(startXPosition + 49, row);
		treesMapChunkTwentyTwo[30]  = new NatureObject(startXPosition + 50, row);
		treesMapChunkTwentyTwo[31]  = new NatureObject(startXPosition + 51, row);
		treesMapChunkTwentyTwo[32]  = new NatureObject(startXPosition + 52, row);
		treesMapChunkTwentyTwo[33]  = new NatureObject(startXPosition + 53, row);
		treesMapChunkTwentyTwo[34]  = new NatureObject(startXPosition + 54, row);
		treesMapChunkTwentyTwo[35]  = new NatureObject(startXPosition + 55, row);
		treesMapChunkTwentyTwo[36]  = new NatureObject(startXPosition + 56, row);
		treesMapChunkTwentyTwo[37]  = new NatureObject(startXPosition + 57, row);
		treesMapChunkTwentyTwo[38]  = new NatureObject(startXPosition + 58, row);
		treesMapChunkTwentyTwo[39]  = new NatureObject(startXPosition + 59, row);
		treesMapChunkTwentyTwo[40]  = new NatureObject(startXPosition + 60, row);
		treesMapChunkTwentyTwo[41]  = new NatureObject(startXPosition + 61, row);
		treesMapChunkTwentyTwo[42]  = new NatureObject(startXPosition + 62, row);
		treesMapChunkTwentyTwo[43]  = new NatureObject(startXPosition + 63, row);
		treesMapChunkTwentyTwo[44]  = new NatureObject(startXPosition + 64, row);
		treesMapChunkTwentyTwo[45]  = new NatureObject(startXPosition + 65, row);
		treesMapChunkTwentyTwo[46]  = new NatureObject(startXPosition + 66, row);
		treesMapChunkTwentyTwo[47]  = new NatureObject(startXPosition + 67, row);
		row 				        = rowThreeStartPosition + 1;
		treesMapChunkTwentyTwo[48]  = new NatureObject(startXPosition + 3, row);
		treesMapChunkTwentyTwo[49]  = new NatureObject(startXPosition + 4, row);
		treesMapChunkTwentyTwo[50]  = new NatureObject(startXPosition + 5, row);
		treesMapChunkTwentyTwo[51]  = new NatureObject(startXPosition + 6, row);
		treesMapChunkTwentyTwo[52]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyTwo[53]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyTwo[54]  = new NatureObject(startXPosition + 45, row);
		row 			            = rowThreeStartPosition + 2;
		treesMapChunkTwentyTwo[55]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyTwo[56]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyTwo[57]  = new NatureObject(startXPosition + 45, row);
		row 			            = rowThreeStartPosition + 3;
		treesMapChunkTwentyTwo[58]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyTwo[59]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyTwo[60]  = new NatureObject(startXPosition + 45, row);
		row 				        = rowThreeStartPosition + 4;
		treesMapChunkTwentyTwo[61]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyTwo[62]  = new NatureObject(startXPosition + 21, row);
		treesMapChunkTwentyTwo[63]  = new NatureObject(startXPosition + 22, row);
		treesMapChunkTwentyTwo[64]  = new NatureObject(startXPosition + 23, row);
		treesMapChunkTwentyTwo[65]  = new NatureObject(startXPosition + 24, row);
		treesMapChunkTwentyTwo[66]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyTwo[67]  = new NatureObject(startXPosition + 45, row);
		treesMapChunkTwentyTwo[68]  = new NatureObject(startXPosition + 46, row);
		treesMapChunkTwentyTwo[69]  = new NatureObject(startXPosition + 47, row);
		treesMapChunkTwentyTwo[70]  = new NatureObject(startXPosition + 48, row);
		treesMapChunkTwentyTwo[71]  = new NatureObject(startXPosition + 49, row);
		row 				        = rowThreeStartPosition + 8;
		treesMapChunkTwentyTwo[72]  = new NatureObject(startXPosition, row);
		treesMapChunkTwentyTwo[73]  = new NatureObject(startXPosition + 1, row);
		treesMapChunkTwentyTwo[74]  = new NatureObject(startXPosition + 2, row);
		treesMapChunkTwentyTwo[75]  = new NatureObject(startXPosition + 3, row);
		treesMapChunkTwentyTwo[76]  = new NatureObject(startXPosition + 7, row);
		treesMapChunkTwentyTwo[77]  = new NatureObject(startXPosition + 10, row);
		treesMapChunkTwentyTwo[78]  = new NatureObject(startXPosition + 15, row);
		treesMapChunkTwentyTwo[79]  = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyTwo[80]  = new NatureObject(startXPosition + 25, row);
		treesMapChunkTwentyTwo[81]  = new NatureObject(startXPosition + 30, row);
		treesMapChunkTwentyTwo[82]  = new NatureObject(startXPosition + 35, row);
		treesMapChunkTwentyTwo[83]  = new NatureObject(startXPosition + 50, row);
		treesMapChunkTwentyTwo[84]  = new NatureObject(startXPosition + 51, row);
		treesMapChunkTwentyTwo[85]  = new NatureObject(startXPosition + 52, row);
		treesMapChunkTwentyTwo[86]  = new NatureObject(startXPosition + 53, row);
		treesMapChunkTwentyTwo[87]  = new NatureObject(startXPosition + 63, row);
		treesMapChunkTwentyTwo[88]  = new NatureObject(startXPosition + 64, row);
		treesMapChunkTwentyTwo[89]  = new NatureObject(startXPosition + 65, row);
		row 				        = rowThreeStartPosition + 9;
		treesMapChunkTwentyTwo[90]  = new NatureObject(startXPosition + 3, row);
		treesMapChunkTwentyTwo[91]  = new NatureObject(startXPosition + 8, row);
		treesMapChunkTwentyTwo[92]  = new NatureObject(startXPosition + 14, row);
		treesMapChunkTwentyTwo[93]  = new NatureObject(startXPosition + 28, row);
		treesMapChunkTwentyTwo[94]  = new NatureObject(startXPosition + 29, row);
		treesMapChunkTwentyTwo[95]  = new NatureObject(startXPosition + 30, row);
		treesMapChunkTwentyTwo[96]  = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyTwo[97]  = new NatureObject(startXPosition + 41, row);
		treesMapChunkTwentyTwo[98]  = new NatureObject(startXPosition + 50, row);
		treesMapChunkTwentyTwo[99]  = new NatureObject(startXPosition + 60, row);
		row 				        = rowThreeStartPosition + 10;
		treesMapChunkTwentyTwo[100] = new NatureObject(startXPosition, row);
		treesMapChunkTwentyTwo[101] = new NatureObject(startXPosition + 4, row);
		treesMapChunkTwentyTwo[102] = new NatureObject(startXPosition + 7, row);
		treesMapChunkTwentyTwo[103] = new NatureObject(startXPosition + 10, row);
		treesMapChunkTwentyTwo[104] = new NatureObject(startXPosition + 13, row);
		treesMapChunkTwentyTwo[105] = new NatureObject(startXPosition + 37, row);
		treesMapChunkTwentyTwo[106] = new NatureObject(startXPosition + 38, row);
		row 				        = rowThreeStartPosition + 19;
		treesMapChunkTwentyTwo[107] = new NatureObject(startXPosition + 20, row);
		treesMapChunkTwentyTwo[108] = new NatureObject(startXPosition + 25, row);
		treesMapChunkTwentyTwo[109] = new NatureObject(startXPosition + 30, row);
		treesMapChunkTwentyTwo[110] = new NatureObject(startXPosition + 40, row);
		treesMapChunkTwentyTwo[111] = new NatureObject(startXPosition + 50, row);
		treesMapChunkTwentyTwo[112] = new NatureObject(startXPosition + 67, row);
		row 				        = rowThreeStartPosition + 20;
		treesMapChunkTwentyTwo[113] = new NatureObject(startXPosition + 67, row);
		row 				        = rowThreeStartPosition + 21;
		treesMapChunkTwentyTwo[114] = new NatureObject(startXPosition + 67, row);
		row 				        = rowThreeStartPosition + 22;
		treesMapChunkTwentyTwo[115] = new NatureObject(startXPosition + 67, row);
		row 				        = rowThreeStartPosition + 24;
		treesMapChunkTwentyTwo[116] = new NatureObject(startXPosition + 5, row);
		treesMapChunkTwentyTwo[117] = new NatureObject(startXPosition + 14, row);
		treesMapChunkTwentyTwo[118] = new NatureObject(startXPosition + 26, row);
		treesMapChunkTwentyTwo[119] = new NatureObject(startXPosition + 33, row);
		treesMapChunkTwentyTwo[120] = new NatureObject(startXPosition + 64, row);
		treesMapChunkTwentyTwo[121] = new NatureObject(startXPosition + 65, row);
		treesMapChunkTwentyTwo[122] = new NatureObject(startXPosition + 66, row);
		treesMapChunkTwentyTwo[123] = new NatureObject(startXPosition + 67, row);
		row 				        = rowThreeStartPosition + 34;
		treesMapChunkTwentyTwo[124] = new NatureObject(startXPosition + 7, row);
		treesMapChunkTwentyTwo[125] = new NatureObject(startXPosition + 15, row);
		treesMapChunkTwentyTwo[126] = new NatureObject(startXPosition + 16, row);
		treesMapChunkTwentyTwo[127] = new NatureObject(startXPosition + 24, row);
		treesMapChunkTwentyTwo[128] = new NatureObject(startXPosition + 36, row);
		treesMapChunkTwentyTwo[129] = new NatureObject(startXPosition + 46, row);
		treesMapChunkTwentyTwo[130] = new NatureObject(startXPosition + 56, row);
		treesMapChunkTwentyTwo[131] = new NatureObject(startXPosition + 66, row);
		row 				        = rowThreeStartPosition + 49;
		treesMapChunkTwentyTwo[132] = new NatureObject(startXPosition + 7, row);
		treesMapChunkTwentyTwo[133] = new NatureObject(startXPosition + 15, row);
		treesMapChunkTwentyTwo[134] = new NatureObject(startXPosition + 16, row);
		treesMapChunkTwentyTwo[135] = new NatureObject(startXPosition + 24, row);
		treesMapChunkTwentyTwo[136] = new NatureObject(startXPosition + 36, row);
		treesMapChunkTwentyTwo[137] = new NatureObject(startXPosition + 46, row);
		treesMapChunkTwentyTwo[138] = new NatureObject(startXPosition + 56, row);
		treesMapChunkTwentyTwo[139] = new NatureObject(startXPosition + 66, row);
		
		addGameObjectsToGameObjectArrayList();
	}

	@Override
	protected void addGameObjectsToGameObjectArrayList() {
		for (int i = 0; i < treesMapChunkTwentyTwo.length; i++) {
			GameObjectLoader.gameObjectList.add(treesMapChunkTwentyTwo[i]);
		}
	}
}
